### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by alexkoss** [bolshakovk/BaltInfoCom#1]
Добрый день, Константин. Меня зовут Александр, представитель БалтИнфоКом.

В рамках вашего тестового задания предоставляю обратную связь. Запускаю на виртуальной машине с 

16 ГБ оперативной,
ubuntu 22.04.2,
Docker version 24.0.1,
Docker Compose version v2.18.1.

Поменял в скрипте ip адреса на свою локальную сеть, но кластер падает сразу после запуска:

```
sentinel@sentinel-vm22:~/test/docker/bolshakovk/BaltInfoCom-main$ date "+%H:%M:%S   %d/%m/%y"
16:36:56   29/05/23
sentinel@sentinel-vm22:~/test/docker/bolshakovk/BaltInfoCom-main$ docker-compose up -d
[+] Building 0.0s (0/0)
[+] Running 3/3
 ✔ Container cassandra1  Started                                                                                                                                                    0.2s
 ✔ Container cassandra2  Started                                                                                                                                                    0.4s
 ✔ Container cassandra3  Started                                                                                                                                                    0.5s
sentinel@sentinel-vm22:~/test/docker/bolshakovk/BaltInfoCom-main$ docker ps
CONTAINER ID   IMAGE              COMMAND                  CREATED          STATUS         PORTS     NAMES
73aca32c4ef6   cassandra:latest   "docker-entrypoint.s…"   6 minutes ago    Up 2 seconds             cassandra2
c501a0a02c79   cassandra:latest   "docker-entrypoint.s…"   6 minutes ago    Up 2 seconds             cassandra3
92c4eda1757b   cassandra:latest   "docker-entrypoint.s…"   16 minutes ago   Up 2 seconds             cassandra1
sentinel@sentinel-vm22:~/test/docker/bolshakovk/BaltInfoCom-main$ date "+%H:%M:%S   %d/%m/%y"
16:37:08   29/05/23
sentinel@sentinel-vm22:~/test/docker/bolshakovk/BaltInfoCom-main$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
sentinel@sentinel-vm22:~/test/docker/bolshakovk/BaltInfoCom-main$ date "+%H:%M:%S   %d/%m/%y"
16:37:12   29/05/23
```

Ошибка из docker logs cassandra1 2 3:

```
ERROR [main] 2023-05-29 13:37:08,522 CassandraDaemon.java:898 - Exception encountered during startup: If rpc_address is set to a wildcard address (0.0.0.0), then you must set broadcast_rpc_address to a value other than 0.0.0.0
```

**Comment by bolshakovk** [comment]
@alexkoss добавил рассылку RPC, проверял логи в docker logs ***, подключился к кластеру docker exec -it cassandra1 cqlsh 192.168.0.2 9042
проверял состояние кластера: docker exec -it cassandra1 nodetool status

**Comment by alexkoss** [comment]
@bolshakovk представим сеть из машин А и Б. На машине А поднято три контейнера. Необходимо подключиться cqlsh с машины Б на второй контейнер.

**Comment by alexkoss** [comment]
@bolshakovk Добрый день, Константин. Будете доделывать тестовое?

**Comment by bolshakovk** [comment]
@alexkoss к сожалению уже получил оффер на новое место, сейчас разбираюсь с документами, по этому вряд ли(

**Comment by bolshakovk** [comment]
> cqlsh

я бы в таком случае на WSL установил cqlsh, и подключился к касандре cqlsh <host> <port> -u <user> -p <password>, если не правильно, хотел бы узнать ответ, интересно) 
Инфу черпал с [сайта](https://www.caclusters.com/docs/cassandra/Connecting%20to%20Cassandra%E2%84%A2%20Server%20via%20Shell1618889130.html) и чата гпт

**Comment by alexkoss** [comment]
Для решения данной задачи необходимо использовать другой сетевой драйвер, macvlan или ipvlan
